INSERT OR IGNORE INTO users (id, email, name, role) VALUES
('user-recovered-01', 'graziellariosmenezes@gmail.com', 'Graziella Rios Menezes', 'member'),
('user-recovered-02', 'marcio@comercialmargutti.com.br', 'Marcio', 'member'),
('user-recovered-03', 'ph@phsholding.com.br', 'PH', 'member'),
('user-recovered-04', 'rzawitoski@gmail.com.br', 'Rzawitoski', 'member'),
('user-recovered-05', 'rzawitoski@gmail.com', 'Rzawitoski', 'member'),
('user-recovered-06', 'renan@dalceroconsultoria.com.br', 'Renan', 'member'),
('user-recovered-07', 'danielle@salesprime.com.br', 'Danielle', 'member'),
('user-recovered-08', 'alexandrebig111@gmail.com', 'Alexandre', 'member'),
('user-recovered-09', 'danilo@emibra.com.br', 'Danilo', 'member'),
('user-recovered-10', 'Danilo@emibra.com.br', 'Danilo', 'member'),
('user-recovered-11', 'ale.moura@cacaushowvaiatevoce.com.br', 'Ale Moura', 'member'),
('user-recovered-12', 'arethusasalomao@gmail.com', 'Arethusa', 'member'),
('user-recovered-13', 'camila.moraes@factorit.com.br', 'Camila Moraes', 'member'),
('user-recovered-14', 'cintia.pellizzaro@bellavidars.com.br', 'Cintia Pellizzaro', 'member'),
('user-recovered-15', 'constanzo@constanzo.com.br', 'Constanzo', 'member'),
('user-recovered-16', 'contato@alemdavoz.com', 'Alem da Voz', 'member'),
('user-recovered-17', 'crsoares@vivametodologia.com', 'CR Soares', 'member'),
('user-recovered-18', 'daniele.kupper@kupperadvocacia.com.br', 'Daniele Kupper', 'member'),
('user-recovered-19', 'fabio.torres@outlook.com.br', 'Fabio Torres', 'member'),
('user-recovered-20', 'franciele.barion@gmail.com', 'Franciele Barion', 'member'),
('user-recovered-21', 'joao.alarcon.jr@gmail.com', 'Joao Alarcon', 'member'),
('user-recovered-22', 'joeruas@gmail.com', 'Joe Ruas', 'member'),
('user-recovered-23', 'julianacglima@hotmail.com', 'Juliana', 'member'),
('user-recovered-24', 'juliane.lara@larafy.com.br', 'Juliane Lara', 'member'),
('user-recovered-25', 'katherine@elevatemedperformance.com', 'Katherine', 'member'),
('user-recovered-26', 'lessandramarques88@gmail.com', 'Lessandra Marques', 'member'),
('user-recovered-27', 'ligiapimenta1@gmail.com', 'Ligia Pimenta', 'member'),
('user-recovered-28', 'marcelo@marcantiadviser.com.br', 'Marcelo', 'member'),
('user-recovered-29', 'marciopedrosa@piccolibambini.com.br', 'Marcio Pedrosa', 'member'),
('user-recovered-30', 'monicacereser@gmail.com', 'Monica Cereser', 'member'),
('user-recovered-31', 'naualelima@gmail.com', 'Nauale Lima', 'member'),
('user-recovered-32', 'raphaelacerqueira.w1@gmail.com', 'Raphaela Cerqueira', 'member'),
('user-recovered-33', 'stefaniebcassis@gmail.com', 'Stefanie Cassis', 'member'),
('user-recovered-34', 'Ariene@helloenglishlovers.com.br', 'Ariene', 'member');

INSERT OR IGNORE INTO user_progress (id, user_id, email, name, form_data, progress_percentage, status) VALUES
('prog-user-recovered-01', 'user-recovered-01', 'graziellariosmenezes@gmail.com', 'Graziella Rios Menezes', '{"mentor":{},"mentee":{},"method":{},"delivery":{}}', 89, 'in_progress'),
('prog-user-recovered-02', 'user-recovered-02', 'marcio@comercialmargutti.com.br', 'Marcio', '{"mentor":{},"mentee":{},"method":{},"delivery":{}}', 0, 'in_progress'),
('prog-user-recovered-03', 'user-recovered-03', 'ph@phsholding.com.br', 'PH', '{"mentor":{},"mentee":{},"method":{},"delivery":{}}', 0, 'in_progress'),
('prog-user-recovered-04', 'user-recovered-04', 'rzawitoski@gmail.com.br', 'Rzawitoski', '{"mentor":{},"mentee":{},"method":{},"delivery":{}}', 0, 'in_progress'),
('prog-user-recovered-06', 'user-recovered-06', 'renan@dalceroconsultoria.com.br', 'Renan', '{"mentor":{},"mentee":{},"method":{},"delivery":{}}', 0, 'in_progress'),
('prog-user-recovered-07', 'user-recovered-07', 'danielle@salesprime.com.br', 'Danielle', '{"mentor":{},"mentee":{},"method":{},"delivery":{}}', 0, 'in_progress'),
('prog-user-recovered-08', 'user-recovered-08', 'alexandrebig111@gmail.com', 'Alexandre', '{"mentor":{},"mentee":{},"method":{},"delivery":{}}', 25, 'in_progress'),
('prog-user-recovered-09', 'user-recovered-09', 'danilo@emibra.com.br', 'Danilo', '{"mentor":{},"mentee":{},"method":{},"delivery":{}}', 0, 'in_progress'),
('prog-user-recovered-10', 'user-recovered-10', 'Danilo@emibra.com.br', 'Danilo', '{"mentor":{},"mentee":{},"method":{},"delivery":{}}', 25, 'in_progress'),
('prog-user-recovered-13', 'user-recovered-13', 'camila.moraes@factorit.com.br', 'Camila Moraes', '{"mentor":{},"mentee":{},"method":{},"delivery":{}}', 25, 'in_progress'),
('prog-user-recovered-14', 'user-recovered-14', 'cintia.pellizzaro@bellavidars.com.br', 'Cintia Pellizzaro', '{"mentor":{},"mentee":{},"method":{},"delivery":{}}', 25, 'in_progress'),
('prog-user-recovered-15', 'user-recovered-15', 'constanzo@constanzo.com.br', 'Constanzo', '{"mentor":{},"mentee":{},"method":{},"delivery":{}}', 25, 'in_progress'),
('prog-user-recovered-17', 'user-recovered-17', 'crsoares@vivametodologia.com', 'CR Soares', '{"mentor":{},"mentee":{},"method":{},"delivery":{}}', 25, 'in_progress'),
('prog-user-recovered-19', 'user-recovered-19', 'fabio.torres@outlook.com.br', 'Fabio Torres', '{"mentor":{},"mentee":{},"method":{},"delivery":{}}', 25, 'in_progress'),
('prog-user-recovered-20', 'user-recovered-20', 'franciele.barion@gmail.com', 'Franciele Barion', '{"mentor":{},"mentee":{},"method":{},"delivery":{}}', 25, 'in_progress'),
('prog-user-recovered-21', 'user-recovered-21', 'joao.alarcon.jr@gmail.com', 'Joao Alarcon', '{"mentor":{},"mentee":{},"method":{},"delivery":{}}', 25, 'in_progress'),
('prog-user-recovered-22', 'user-recovered-22', 'joeruas@gmail.com', 'Joe Ruas', '{"mentor":{},"mentee":{},"method":{},"delivery":{}}', 25, 'in_progress'),
('prog-user-recovered-24', 'user-recovered-24', 'juliane.lara@larafy.com.br', 'Juliane Lara', '{"mentor":{},"mentee":{},"method":{},"delivery":{}}', 25, 'in_progress'),
('prog-user-recovered-25', 'user-recovered-25', 'katherine@elevatemedperformance.com', 'Katherine', '{"mentor":{},"mentee":{},"method":{},"delivery":{}}', 25, 'in_progress'),
('prog-user-recovered-26', 'user-recovered-26', 'lessandramarques88@gmail.com', 'Lessandra Marques', '{"mentor":{},"mentee":{},"method":{},"delivery":{}}', 25, 'in_progress'),
('prog-user-recovered-27', 'user-recovered-27', 'ligiapimenta1@gmail.com', 'Ligia Pimenta', '{"mentor":{},"mentee":{},"method":{},"delivery":{}}', 25, 'in_progress'),
('prog-user-recovered-29', 'user-recovered-29', 'marciopedrosa@piccolibambini.com.br', 'Marcio Pedrosa', '{"mentor":{},"mentee":{},"method":{},"delivery":{}}', 0, 'in_progress'),
('prog-user-recovered-30', 'user-recovered-30', 'monicacereser@gmail.com', 'Monica Cereser', '{"mentor":{},"mentee":{},"method":{},"delivery":{}}', 25, 'in_progress'),
('prog-user-recovered-31', 'user-recovered-31', 'naualelima@gmail.com', 'Nauale Lima', '{"mentor":{},"mentee":{},"method":{},"delivery":{}}', 25, 'in_progress'),
('prog-user-recovered-33', 'user-recovered-33', 'stefaniebcassis@gmail.com', 'Stefanie Cassis', '{"mentor":{},"mentee":{},"method":{},"delivery":{}}', 25, 'in_progress'),
('prog-user-recovered-34', 'user-recovered-34', 'Ariene@helloenglishlovers.com.br', 'Ariene', '{"mentor":{},"mentee":{},"method":{},"delivery":{}}', 25, 'in_progress');

SELECT email, name, progress_percentage, status FROM user_progress ORDER BY progress_percentage DESC;
